### PR TITLE
Fix contributor deactivated_by_user_id being set on any udpate

### LINKED ISSUE #1884: [BUG] Updating any contributor attr sets deactivated_by_user to current_user
### Steps to reproduce
* Go to a contributor show page
* Add a tag
* Check the deactivated_by_user_id attr

### PR DESCRIPTION
**Pull request by mattwr18**
Fixes #1884

### CODE REVIEW

File: app/controllers/admin/contributors_controller.rb [hunk 1]
```diff
@@ -4,22 +4,36 @@ module Admin
   class ContributorsController < Admin::ApplicationController
     include AdministrateExportable::Exporter
 
-    def update
-      contributor = Contributor.find(update_params[:id])
-      contributor.deactivated_by_admin = !ActiveModel::Type::Boolean.new.cast(update_params[:contributor][:active])
+    before_action :set_contributor, only: :update
+    before_action :toggle_active_state, only: :update
```
Comment (soey) [inline app/controllers/admin/contributors_controller.rb:8]: why this in a before action

File: app/controllers/contributors_controller.rb [hunk 2]
```diff
@@ -5,6 +5,7 @@ class ContributorsController < ApplicationController
   before_action :contributors_sidebar, only: %i[show update]
   before_action :count_params, only: :count
   before_action :contributors_params, only: :index
+  before_action :toggle_active_state, only: :update
```
Comment (soey) [inline app/controllers/contributors_controller.rb:8]: why using a before action?
