### PR TITLE
fix: Use the most recent request as fallback

### LINKED ISSUE #215: Answers by Users will be dropped if the user has never received a request
Right now, we're onboarding new users. If a user has never received an initial question, then any messages to the Telegram Bot and any Email to Sendgrid will be silently dropped.

**Expected Behaviour**:
No message should be dropped. 
Either:
* The user gets a feedback: "Wait for us ...."
* Or a message will be saved to the most recent request, even if the user actually has never seen the request.

### PR DESCRIPTION
**Pull request by roschaefer**
As requested by @drjakob
https://github.com/tactilenews/100eyes/issues/215#issuecomment-645019491

fix #215

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -46,7 +46,7 @@ def channels
   end
 
   def active_request
-    received_requests.reorder(created_at: :desc).first
+    received_requests.reorder(created_at: :desc).first || Request.reorder(created_at: :desc).first
```
Comment (tillprochaska) [inline app/models/user.rb:49]: I think that’s just equivalent to the following:

```suggestion
    Request.reorder(created_at: :desc).first
```

Two cases:

* A user has never received a request, then it’ll be the most recent request as a fallback
* A user has received a request, then it’ll be the most recent request, as all user’s receive the same requests.

Do we still need an active request per user? I think from a UX perspective, right now, editors already expect the question to be the same for all users at the same time. So why don't we use `Request.active` as we did previously?

**Comment by tillprochaska** [comment]
With this fix, messages will still be dropped if no request has ever been sent. I think we should handle that case as well: Either bounce the message, or alternatively, save them without an associated request (also then, we wouldn’t have a UI for it). Will open a separate issue.

File: app/models/user.rb (hunk 1 above)
Comment (roschaefer) [reply app/models/user.rb:49]: @drjakob @FrauCsu I talked with @tillprochaska about this problem. I don't really like this solution in this PR nor do I like the solution proposed here by Till.

For the future: Would be a reasonable solution to automatically send the user on registration (via Mail or Telegram) the most recent request as a message? So the user always knows, what he/she is responding to?

I'm going to merge this as it is for now.
