### PR TITLE
Fix sending emails with commas in their sender name.

### LINKED ISSUE #1341: Emails fail to send if the project name / sender name contains a comma
See sentry 100EYES-3E.

A sender name containing a comma gets interpreted as a list of multiple sender names, which can be specified in the `from:` field in the email header according to [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322#section-3.6.2).
To handle sender names with a comma in them correctly the comma in it needs to be escaped, e.g. by quoting the whole sender name.

### PR DESCRIPTION
**Pull request by phoeinx**
To comply with RFC 5322 (https://www.rfc-editor.org/rfc/rfc5322#section-3.6.2) where commas in the from: field specify a list of multiple senders, we need to escape commas in the sender name. This is necessary if a project specifies its project name and therefore the sender name, e.g. as 'Coffee, and you?'.

Closes #1341.

### CODE REVIEW

**Comment by drjakob** [comment]
yes, lets test outbound_spec

**Comment by phoeinx** [comment]
Thanks for the reminder! I added a regression test.

File: spec/adapters/postmark_adapter/outbound_spec.rb [hunk 1]
```diff
@@ -74,6 +74,14 @@
 
         subject { message_email[:from].formatted }
         it { should eq(['TestingProject <100eyes-test-account@example.org>']) }
```
Comment (tillprochaska) [inline spec/adapters/postmark_adapter/outbound_spec.rb:76]: I was wondering why this test doesn’t fail with that change? Shouldn’t this be `"TestingProject" <100eyes-test-account@example.org>` (with quotes)?

File: spec/adapters/postmark_adapter/outbound_spec.rb [hunk 2]
```diff
@@ -74,6 +74,14 @@
...
+
+        context 'with a comma / list separator in the project name' do
+          before do
+            allow(Setting).to receive(:project_name).and_return('TestingProject, with a comma!')
+          end
```
Comment (tillprochaska) [inline spec/adapters/postmark_adapter/outbound_spec.rb:81]: Not sure if the line break was mandated by rubocop, but in general I prefer the `{ … } ` block syntax for single-line blocks.

```suggestion
          before { allow(Setting).to receive(:project_name).and_return('TestingProject, with a comma!') }
```

File: spec/adapters/postmark_adapter/outbound_spec.rb (hunk 1 above)
Comment (tillprochaska) [reply spec/adapters/postmark_adapter/outbound_spec.rb:76]: Never mind, I didn’t notice that this doesn’t test for the raw `From` header, but for the `formatted` value, which parses, then converts back to a string again, which only adds quotes if needed.

https://github.com/mikel/mail/blob/22a7afc23f253319965bf9228a0a430eec94e06d/lib/mail/elements/address.rb#L47

**Review by tillprochaska — APPROVED** [review]
