### PR TITLE
Avoid infinite loop in postmark

### LINKED ISSUE #1941: [BUG] If Postmark::InactiveRecipientError is called with an admin's email it gets stuck in a loop
### Steps to reproduce

* Probably best not to, but if you try to send a message to an email that has unsubscribed, it will try to send out the contributor marked inactive email, which will trigger the error and get caught in an infinite loop.

We should check to see that the email we are sending a notification about is not the email that unsubscribed.

### PR DESCRIPTION
**Pull request by mattwr18**
if we try to send a message to an admin notifying them that a contributor is inactive, but that admin has the same email as the contributor who has unsubscribed, it gets stuck in an infinite loop

Fixes #1941

### CODE REVIEW

File: spec/adapters/postmark_adapter/outbound_spec.rb [hunk 1]
```diff
@@ -288,5 +288,62 @@
...
+      context 'user, not admin' do
+        let(:admin) { build(:user) }
+        let(:contributor) { create(:contributor) }
+
+        it 'does not enqueue a Mailer' do
+          expect { subject }.not_to have_enqueued_job
+        end
+      end
+
+      context 'admin email equals contributo marked inactive email' do
```
Comment (roschaefer) [inline spec/adapters/postmark_adapter/outbound_spec.rb:322]:
```suggestion
      context 'admin email equals contributor email' do
```

File: spec/adapters/postmark_adapter/outbound_spec.rb [hunk 2]
```diff
@@ -288,5 +288,62 @@
...
+      context 'no contributor' do
+        let(:admin) { build(:user, admin: true) }
+        let(:contributor) { nil }
+
+        it 'does not enqueue a Mailer' do
+          expect { subject }.not_to have_enqueued_job
+        end
+      end
+
+      context 'user, not admin' do
```
Comment (roschaefer) [inline spec/adapters/postmark_adapter/outbound_spec.rb:313]:
```suggestion
      context 'user has no admin role' do
```

File: spec/adapters/postmark_adapter/outbound_spec.rb [hunk 3]
```diff
@@ -288,5 +288,62 @@
...
+        let(:contributor) { create(:contributor) }
+
+        it 'does not enqueue a Mailer' do
+          expect { subject }.not_to have_enqueued_job
+        end
+      end
+
+      context 'admin email equals contributo marked inactive email' do
+        let(:admin) { build(:user, id: 231_123, admin: true, email: 'my-email@example.org') }
+        let(:contributor) { build(:contributor, id: 231_123, email: 'my-email@example.org') }
```
Comment (roschaefer) [inline spec/adapters/postmark_adapter/outbound_spec.rb:324]:
```suggestion
        let(:admin) { build(:user, admin: true, email: 'my-email@example.org') }
        let(:contributor) { build(:contributor, email: 'my-email@example.org') }
```

Why the hard-coded id? I would expect it's not relevant? Users and contributors are two different models, or did I miss something?

File: spec/adapters/postmark_adapter/outbound_spec.rb [hunk 4]
```diff
@@ -288,5 +288,62 @@
...
+
+        it 'does not enqueue a Mailer' do
+          expect { subject }.not_to have_enqueued_job
+        end
+      end
+
+      context 'with an admin and contributor' do
```
Comment (roschaefer) [inline spec/adapters/postmark_adapter/outbound_spec.rb:331]:
```suggestion
      context 'with an admin and contributor who do not have the same email address' do
```

**Review by roschaefer — CHANGES_REQUESTED** [review]
I love the bug that we're fixing here. It's so silly.

full circle

Nevertheless I requested some changes. Everything is just a wording issue except the primary keys on line 323 and 324. Without this, I would have hit approve.

File: spec/adapters/postmark_adapter/outbound_spec.rb (hunk 3 above)
Comment (mattwr18) [reply spec/adapters/postmark_adapter/outbound_spec.rb:324]: It was just to avoid creating the records. If we just build them, no ids are issued and that results in a serialization error.

Comment (roschaefer) [reply spec/adapters/postmark_adapter/outbound_spec.rb]: Ok, what about `create` instead of `build`?

I was just confused, I thought it has something to do with the feature itself.
